### ISSUE TITLE
Project Plans

### ISSUE THREAD

**Issue by antfu** [eslint-stylistic/eslint-stylistic#1]
So the current plan is to port rules from both https://github.com/eslint/eslint and https://github.com/typescript-eslint/typescript-eslint. 

They will be released as `@eslint-stylistic/eslint-plugin-core` and `@eslint-stylistic/eslint-plugin-typescript` respectively. 

I also reserved `eslint-config-stylistic` for a one-line `extend` in `eslintrc` and easy usage. Ideally, the usage would be like:

```json
{
  "extends": ["stylistic"]
}
```

---

## Project Stages

Track on https://eslint-stylistic.netlify.app/contribute/project-progress

----

## Current Focus

We shall focus on porting the ESLint core first, here is a few todos:

- [x] Port Rules from ESLint core
  - [x] Migration Scripts
  - [x] Docs
  - [x] Docs Improvements
  - [x] Invite contributors who are interested in maintaining them, or previously contributed to those rules
- [x] Port Rules from `typescript-eslint`
  - [x] Would be glad to use some help from the `typescript-eslint` team, if anyone is interested
- [x] Migration tools, to print warning on legacy rules.

**Comment by Shinigami92** [comment]
In preparation of https://www.npmjs.com/package/@eslint/js I would suggest to not name it core

**Comment by antfu** [comment]
> In preparation of [npmjs.com/package/@eslint/js](https://www.npmjs.com/package/@eslint/js) I would suggest to not name it core

Oh interesting, thanks for the heads up! Do you suggest we go with `@eslint-stylistic/eslint-plugin-js/ts` or `@eslint-stylistic/eslint-plugin-javascript/typescript`?

**Comment by xbmlz** [comment]
> > In preparation of [npmjs.com/package/@eslint/js](https://www.npmjs.com/package/@eslint/js) I would suggest to not name it core
> 
> Oh interesting, thanks for the heads up! Do you suggest we go with `eslint-plugin-(js/ts)` or `eslint-plugin-(javascript/typescript)`?

I think it's still js or ts, and this naming is already very common for web developers ^-^

**Comment by Shinigami92** [comment]
> > In preparation of [npmjs.com/package/@eslint/js](https://www.npmjs.com/package/@eslint/js) I would suggest to not name it core
> 
> Oh interesting, thanks for the heads up! Do you suggest we go with `eslint-plugin-(js/ts)` or `eslint-plugin-(javascript/typescript)`?

I personally prefer the explicit naming `@eslint-stylistic/eslint-plugin-javascript` and `@eslint-stylistic/eslint-plugin-typescript`,
but I will leave the final decision to you

**Comment by ota-meshi** [comment]
I have a small question. Why separate plugins for `js` and `ts`? `ts` is a superset of `js`, so I think all `ts` rules support `js`.
For example, I think that the indentation rules of `@eslint-stylistic/eslint-plugin` can also support `js` if it supports `ts`.
If a rule requires type information, it might be better to separate the plugin, but I would expect that most stylistic rules do not require type information.

**Comment by Shinigami92** [comment]
> I have a small question. Why separate plugins for `js` and `ts`? `ts` is a superset of `js`, so I think all `ts` rules support `js`. For example, I think that the indentation rule of `@eslint-stylistic/eslint-plugin` can also support `js` if it supports `ts`. If a rule requires type information, it might be better to separate the plugin, but I would expect that most stylistic rules do not require type information.

What about Flow? Or CoffeeScript? Or whatever... 🤔 Aren't they "just" JS with extras? 😅 

It would have up- and downsides to have JS/TS mixed in one plugin
The JS code could be traversed much faster then the TS AST, and maybe there are some projects that explicitly only want JS without TS but using JSDocs for expressing the types.

**Comment by ota-meshi** [comment]
We may need to separate plugins for CoffeeScript and Flow. However, I think `ts` rules can support `js`.
If the same rules as `ts` rules are reimplemented for `js`, there will be two rule implementations, so I'm concerned that the maintenance cost may increase. 
Separating plugins for `js` may have a small performance advantage, but I think lower maintenance costs should be a priority.

**Comment by Shinigami92** [comment]
> We may need to separate plugins for CoffeeScript and Flow. However, I think `ts` rules can support `js`. If the same rules as `ts` rules are reimplemented for `js`, there will be two rule implementations, so I'm concerned that the maintenance cost may increase. Separating plugins for `js` may have a small performance advantage, but I think lower maintenance costs should be a priority.

understandable arguments
let's see what @antfu has to say about that

**Comment by antfu** [comment]
@ota-meshi A few reasons I can think about:

- We are going to port `js` rules from ESLint core, and `ts` rules from `typescript-eslint`, which means they come from different sources and have different structure/format (e.g. eslint rules are single-file JS, while I image typescript ones they are written in typescript with their own plugin-utils). It's easier we separate them for both communication and maintainability.
- While TS is indeed a superset of JS, I imagine `@typescript-eslint/indent` would not be 100% identical to `indent`. If we don't provide the JS version, it might make the migration way harder.
- AFAIK, `@typescript-eslint/eslint-plugin` requires `typescript` as a dependency. Which not all projects would have it installed.

To me, the current priority is to make 1:1 port of existing rules and not to think too much about improvements, so the migration can be easier and straightforward. After it get stable and the both ESLint and ts-eslint teams started to redirecting users to us, then we can thinking about how to (refactor/add more rules/improve existing ones/etc).

**Comment by Shinigami92** [comment]
Yeah, I agree

Additionally: with eslint FlatConfig it will be more and more easy to configure rules for each language individually.

@sxzz might know stuff better specific to FlatConfig
He worked on eslint-define-config for FlatConfig support

**Comment by ota-meshi** [comment]
@antfu  Thank you for your opinion.
I think you're right that separating plugins makes porting and migration easier. Your input made me think that separating the plugins is the best start.

> AFAIK, `@typescript-eslint/eslint-plugin` requires typescript as a dependency. Which not all projects would have it installed.


In my opinion, `@typescript-eslint/utils` is the only dependency.
The rules require a parser, but I think we can also make it independent of `typescript` by making `@babel/eslint-parser` selectable instead of `@typescript-eslint/parser`.

**Comment by kecrily** [comment]
I'm interested in this project, and I've had the idea of maintaining separate style rules, but never acted on it because of energy and time issues. What would it take to join in on this?

---

Also don't forget to integrate issues that have been identified in the original rules but not yet fixed, for example, the indent rule has [eight open issues](https://github.com/eslint/eslint/issues?q=is%3Aissue+is%3Aopen+label%3Aindent+sort%3Aupdated-desc),

---

Regarding package naming, I suggest using `@eslint-stylistic/*` (`@eslint-stylistic/js`), which is similar to `@eslint/js` and is not cumbersome with repeated occurrences of `eslint`.  It doesn't quite keep its conventions but I don't think it's a big problem.

**Comment by antfu** [comment]
Hey @kecrily, glad to hear that. Just send you the invite, welcome :)

---

> Also don't forget to integrate issues that have been identified in the original rules but not yet fixed

I wouldn't really bother with it. Instead, I'd think it would be better for the community to bring them up again in this repo, if they are important enough to them. I think we better do it when we finished the migration and infra.

---

> Regarding package naming

I actually got the `@stylistic` org on npm, so awe could have `@stylistic/js/indent`, which I think it's quite clear now.

<img width="1160" alt="image" src="https://github.com/eslint-stylistic/eslint-stylistic/assets/11247099/3b809e59-adc8-45d5-82ac-9db34d921635">

You can join chat.antfu.me, that we have a channel for this org (later we will see if it needs to be a dedicate server)

**Comment by so1ve** [comment]
After we started maintaining these rules, shall we convert those rules written in JavaScript into TypeScript? This can reduce some potential errors. I'm glad to contribute to this refactor :)

**Comment by antfu** [comment]
Yes, definitely

**Comment by antfu** [comment]
Added a section about refactor plans: https://eslint-stylistic.netlify.app/contribute/project-progress#_4-refactors suggestions welcome :)

**Comment by ljharb** [comment]
I'd love to help; the airbnb config as well as my personal config will need to be able to use stylistic eslint rules (which are far superior to any extant formatters) moving forwar.

**Comment by antfu** [comment]
@ljharb Glad to hear you are interested in it! Since you are here:

- Do you think it makes sense to also move some JSX-related stylistic rules from `eslint-plugin-react` to this repo? The main reason for that is I think it would be better to have a plugin for framework-agnostic JSX rules. So the other frameworks like Solid, Qwik don't need to maintain they are own stylistic rules, and focus more on providing framework-specific rules.
- I hear that you might need to support down to Node 4 for some project (including your eslint config, or not?). For this project, because it's mainly for ESLint v8's deprecation, I think it makes better sense that our compatibility range would align with ESLint (`^12.22.0 || ^14.17.0 || >=16.0.0`). Are you ok with that?

**Comment by ljharb** [comment]
For the first question, it might make sense eventually to replace some of the react rules with framework-agnostic jsx rules, but in general I think many of the rules are indeed framework-specific, including in terms of sub-ecosystem idioms.

For the second, I need to lint projects that *run* in node _0_.4, but I don't need to run the _linter_ in old node versions, if that makes sense? In other words, I need to be able to enforce stylistic conventions on ES3 code, but it's fine if I need a modern node version to do that enforcement.

**Comment by antfu** [comment]
For JSX, I think we only need to have common stylistic rules, basically like how Prettier handles JSX. We picked a few rules https://github.com/eslint-stylistic/eslint-stylistic/blob/93c5b521b16f7777449cd4c6bfe18e78075c4c0d/scripts/migrate.ts#L123-L144 and seems to work fine with JSX for other frameworks. Do you think that list makes sense (what more to include/exclude)? If we do so, would you consider deprecating those rules in `eslint-plugin-react` (or moving them as a dependency to this project) like ESLint and `typescript-eslint` will do?

For the second, that makes sense! I guess as long as the underlying parsers are compatible with ES3, I think we should be fine with that right?

**Comment by ljharb** [comment]
A soft deprecation might be fine, but I'm unlikely to make a breaking change.

Stylistic rules in `eslint-plugin-import` might be worth porting as well, although `import/order` would require supporting import resolvers.

**Comment by antfu** [comment]
Closing this issue as we have moved forward a lot now. Future discussions can be held in separate issues.
