### ISSUE TITLE
Additional package for new rules

### ISSUE THREAD

**Issue by antfu** [eslint-stylistic/eslint-stylistic#136]
To make my personal day-to-day ESLint experience better, I created my personal plugin https://github.com/antfu/eslint-plugin-antfu to handle some edge cases.

Some formatting rules are quite straightforward but never presented in the ESLint/typescript-eslint rules. For example:

- [`generic-spacing`](https://github.com/antfu/eslint-plugin-antfu/blob/77b898f7a2d448e803d9eac4278bb4edeabf8364/src/rules/generic-spacing.test.ts)
- [`named-tuple-spacing`](https://github.com/antfu/eslint-plugin-antfu/blob/ce48a09f9495e9ef14d4ddc7c89ceaea239233d7/src/rules/named-tuple-spacing.test.ts)
- [`indent-binary-ops`](https://github.com/antfu/eslint-plugin-antfu/blob/b7399c27b277e91ae69e3654906ead405ff31294/src/rules/indent-binary-ops.md) - (It's quite useful!)

I assume it might be because both projects have [frozen the stylistic rules since 2020](https://eslint.org/blog/2020/05/changes-to-rules-policies/#what-are-the-changes). Now with ESLint Stylistic, the door finally open up a bit.

I want to keep the current `js` `ts` `jsx` packages as-is to keep the "1:1" migration mapping in v1.0. So I imagine we could have a separate package like `@stylistic/eslint-plugin-extra` to host new rules. Later we plan to merge all those 4 packages into a single one, as currently exposed at `@stylistic/eslint-plugin`.

While I do NOT want to allow any rules to come in and eventually burn out by maintenance burden - so even we are opening the door for new rules, we will be very strict about them. In principle, we'd suggest releasing the proposed rules as separate eslint-plugin to verify them in various codebases first. And later we could start discussing about moving them into this project.

**Comment by Namchee** [comment]
Will this be included as pre-generated configs? I'm thinking of something like `plus-flat` and `plus-legacy`.

**Comment by antfu** [comment]
Yes, when a new rule is added, they can add the config to the preset. I don't think we would need new variations of `plus-*`, but could directly go `recommended-*`
