### ISSUE TITLE
False positive for keyword-spacing rule

### ISSUE THREAD

**Issue by Eugeno** [eslint-stylistic/eslint-stylistic#156]
Class methods:
![image](https://github.com/eslint-stylistic/eslint-stylistic/assets/23382920/827e4adf-61a8-434e-ac72-e11631c2d340)
Version 1.3.1, version 1.2.0 did not have this problem.

**Comment by kecrily** [comment]
Can you create a minimal replication based on this template?

https://stackblitz.com/edit/eslint-stylistic-eslint-stylistic-rwmcqm?file=playground%2Feslint.config.js
