### ISSUE TITLE
Contradicting doc (option "always") for semicolon

### ISSUE THREAD

**Issue by Splines** [eslint-stylistic/eslint-stylistic#163]
In the docs for [`semi`](https://eslint.style/rules/js/semi), you state that `always` was the default option.

https://github.com/eslint-stylistic/eslint-stylistic/blob/62a83bb5f07542806edba778bbfe334a18bbd4c8/packages/eslint-plugin-js/rules/semi/README.md?plain=1#L78

However, when I use the following configuration in `.eslintrc.js`:
```js
const stylistic = require("@stylistic/eslint-plugin");

const customized = stylistic.configs.customize({
  indent: 2,
  quotes: "double",
});

module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 2024,
    sourceType: "module",
  },
  env: {
    browser: true,
    jquery: true,
  },
  extends: "eslint:recommended",
  plugins: [
    "@stylistic",
  ],
  rules: {
    ...customized.rules,
    "no-unused-vars": "warn",
  },
};
```

I get errors for having semicolons ("Extra semicolon"), such that I manually have to set
```js
const customized = stylistic.configs.customize({
  indent: 2,
  quotes: "double",
  semi: "always",
});
```

I don't know but maybe this is related to this line?

https://github.com/eslint-stylistic/eslint-stylistic/blob/62a83bb5f07542806edba778bbfe334a18bbd4c8/packages/eslint-plugin-js/configs/disable-legacy.ts#L59

**Comment by antfu** [comment]
`always` is the rule's default value. This means that if you do `'semi': 'error'` it will be `always`. While you are using the config preset, and the default is false, which is stated in https://eslint.style/guide/config-presets#pre-configured

**Comment by Splines** [comment]
Ok thanks, then I misunderstood the docs for the [Configuration Factory](https://eslint.style/guide/config-presets#configuration-factory):

> We want to provide shared configurations to simplify the usage, while still allowing you to customize the rules to your own preferences.

I understood it like this: "if you don't specify the key, we will use our default value, otherwise you can customize it by specifying the key yourself". But apparently that's not the case.

Is there a way to import all of the style rules without having to manually specifying each key in the config? I haven't seen such an option yet.

**Comment by antfu** [comment]
I am not sure if you really want to enable all rules, but sure we could have a preset for that

**Comment by antfu** [comment]
Opened https://github.com/eslint-stylistic/eslint-stylistic/issues/164 for tracking that
