### ISSUE TITLE
`all` configs preset

### ISSUE THREAD

**Issue by antfu** [eslint-stylistic/eslint-stylistic#164]
### Clear and concise description of the problem

Ref: https://github.com/eslint-stylistic/eslint-stylistic/issues/163

### Suggested solution

Introduce `all-flat` and `all-legacy` configs that simply enable all rules with their default configs.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/setup).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Splines** [comment]
Thanks for opening this! In my opinion, such an option would be very useful if one just wants to have some good stylistic defaults without having to go through every option one by one. If one then notices that one particular rule is not suited, one could still deactivate just this one rule.

By the way, that's the way I expected things to work ("out of the box") when I read this in the [docs](https://eslint.style/guide/config-presets#shared-configurations), but maybe that's just me ;)

> [ESLint shareable configurations](https://eslint.org/docs/latest/extend/shareable-configs) exist to provide a comprehensive list of rules settings that you can start with. ESLint Stylistic maintains a few built-in configurations that you can use out of the box, or as the foundation for your own custom configuration.
