### ISSUE TITLE
Enhance `default` package docs with TS-extended options and behavior

### ISSUE THREAD

**Issue by park-jemin** [eslint-stylistic/eslint-stylistic#178]
Some of the rules that are extended through the TS package have incomplete documentation in the default rule docs. It's currently difficult to go back and forth between the default rule page and the TS rule page (or @typescript-eslint's page) to reference extended options and whether certain behavior is supported - which is a pain point for adoption.

Rules with extended options include (not exhaustive, but covers the ones I'm encountering while setting up a config):
- [`comma-dangle`](https://eslint.style/rules/ts/comma-dangle)
- [`padding-line-between-statements`](https://eslint.style/rules/ts/padding-line-between-statements)
- [`lines-around-comment`](https://eslint.style/rules/ts/lines-around-comment)
- [`lines-between-class-members`](https://eslint.style/rules/ts/lines-between-class-members)

It's also not entirely clear whether certain behavior has been extended. One issue I found in the past was when our team tried enforcing `"allman"` through [`@typescript-eslint/brace-style`](https://typescript-eslint.io/rules/brace-style/) - it had an unintended effect of forcing our interfaces to adhere to this style, which forced us to turn off the override (yes, we're aware of other issues with this setting lol).

```ts
// This is what we wanted
if (bool)
{
  ...
}

// This was incorrect
interface A {
  ...
}

// But this was ok!
type B = {
  ...
}
```

So it would be nice to also be alerted ahead of time if a `default` rule will have behavior beyond what's expected on the docs.

With how our docs our set up in [metadata](https://github.com/eslint-stylistic/eslint-stylistic/blob/af433a8b719076fad657457a4a2adb3b3045f04e/packages/metadata/src/metadata.ts), it would be nice to have your input on how to proceed @antfu

**Comment by antfu** [comment]
They now have a `TypeScript Specific` section (if any) in the docs: https://eslint.style/rules/default/comma-dangle#typescript-specific
