### ISSUE TITLE
docs: enhance rules documentation

### ISSUE THREAD

**Issue by Namchee** [eslint-stylistic/eslint-stylistic#179]
### Clear and concise description of the problem

Currently, the documentation page does not show:

1. `fixable`
2. `hasSuggestion`

although both [ESLint documentation](https://eslint.org/docs/latest/rules/) and [TypeScript ESLint documentation](https://typescript-eslint.io/rules/) shows this. It would be nice if the documentation site shows this so users don't have to navigate back and forth to ESLint or TypeScript ESLint to check whether a deprecated rule is fixable or not.

> This issue stems from [this discussion](https://discord.com/channels/1168956330468450334/1175903995345240064/1175931835516207174)

### Suggested solution

Add 2 new columns that signifies `fixable` and `hasSuggestions`

### Additional context

I can work on this

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Namchee** [comment]
Seems like the `hasSuggestions` property isn't defined in the original JS rules. I'll add them manually for now since I think we deleted the original import script.

**Comment by Namchee** [comment]
I think stylistic rules never have suggestions in the first place except `padding-line-between-statements`. @antfu , do you think the `hasSuggestions` should still be added?

**Comment by antfu** [comment]
IMO having fixable is enough
