### ISSUE TITLE
brace-style recommended options different to default options in docs

### ISSUE THREAD

**Issue by suppayami** [eslint-stylistic/eslint-stylistic#184]
## Description
In documentation, `brace-style` default options are `1tbs` and `"allowSingleLine": false` but in recommended config factory is `stroustrup` and `"allowSingleLine": true`. This leads to some confusing.

## Code location
https://github.com/eslint-stylistic/eslint-stylistic/blob/cb1db1ba50732155f1b7a7f83342a9105fc138d8/packages/eslint-plugin/configs/customize.ts#L64

**Comment by antfu** [comment]
We already discussed that in https://github.com/eslint-stylistic/eslint-stylistic/issues/163 and introduced a `all-flat` config that follows all the defaults. Rules' default might make sense at rule level, but putting together it might not always have the best outcome.

For example, here is the output comparison:
- `all`: https://github.com/eslint-stylistic/eslint-stylistic/blob/main/tests/configs/fixtures/output/all/typescript.ts
- `recommended`: https://github.com/eslint-stylistic/eslint-stylistic/blob/main/tests/configs/fixtures/output/default/typescript.ts

If you think anything in the docs can help avoid such confusing, PR would be greatly appreciated!

**Comment by MetRonnie** [comment]
@antfu I find this rather confusing. It is not clear what the configuration factory is giving you, and it seems to me that there is no reason to use it when you can just use `recommended-flat` or `all-flat` and customise the rules anyway

**Comment by antfu** [comment]
You can use https://github.com/eslint/config-inspector to inspect and see.

It's ok that is not useful to you - do what makes sense to you.

Please don't comment on a close issue, and please avoid directly pinging. Thanks.
