### ISSUE TITLE
rule for enforcing spacing before and after equal (=) sign (assignation)

### ISSUE THREAD

**Issue by otaxhu** [eslint-stylistic/eslint-stylistic#187]
### Clear and concise description of the problem

I couldn't find a rule in the docs [https://eslint.style/packages/js](https://eslint.style/packages/js) (docs of the "js" sub-package) for doing what I'm saying in the title of this issue, so that's it.

If you know about a rule to do exactly this, feel free to close this issue and please tell me.

Have a good day.

### Suggested solution

I can't figure out a proper name for this eslint rule.

### Additional context

Maybe the docs don't show all of the rules or very new rules.

link from where I took the docs [https://eslint.style/packages/js](https://eslint.style/packages/js)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ljharb** [comment]
The core rules https://eslint.org/docs/latest/rules/operator-linebreak combined with https://eslint.org/docs/latest/rules/space-infix-ops would handle this, and both should be present here.

**Comment by otaxhu** [comment]
thanks, the `"space-infix-ops"` rule worked! I tested the other one but do nothing but anyways thanks.

Btw I used `"space-infix-ops"` from `@stylistic/eslint-plugin-js` and no directly from eslint rules since it is deprecated
