### ISSUE TITLE
`indent` does not work well with `eslint-plugin-mdx`

### ISSUE THREAD

**Issue by JounQin** [eslint-stylistic/eslint-stylistic#215]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

From https://github.com/antfu/eslint-config/pull/347 and https://github.com/antfu/eslint-config/pull/353/files#r1420692632

![image](https://github.com/eslint-stylistic/eslint-stylistic/assets/8336744/e52f0c7d-c990-4142-b312-8239ff7b9056)

### Reproduction

https://github.com/antfu/eslint-config

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Trying to dig a little bit, it seems that the indent rules reads all tokens:
https://github.com/eslint-stylistic/eslint-stylistic/blob/82efdd52372930b854ab3b0227b639db456179c5/packages/eslint-plugin-js/rules/indent/indent.ts#L182-L186

While `eslint-mdx` produces `program.body` that only contains JS statements, some markdown notes are presented in the `tokens`:

<img width="710" alt="image" src="https://github.com/eslint-stylistic/eslint-stylistic/assets/11247099/70fdd477-118d-4eb7-8c2c-baa481026c5e">

I wonder if those tokens are used somewhere, is it possible to filter them out, or provide an options to omit them?

**Comment by JounQin** [comment]
> I wonder if those tokens are used somewhere, is it possible to filter them out, or provide an options to omit them?

The tokens are there because they should? Maybe `indent` is not meant to be used on `.mdx`, so then feel free to close. If it wants to support other files, then that's `indent` rule's mission.

**Comment by antfu** [comment]
It basically means that the `source.ast.body` and `source.ast.tokens` are misaligned in the past produced to by `eslint-mdx`. If `eslint-mdx` trying to produce an AST compatible with the ESTree that can be handled by other rules, I believe this is not expected.

And for the record, this is how `indent` rule works in ESLint core. We haven't changed anything about it.

**Comment by JounQin** [comment]
> And for the record, this is how indent rule works in ESLint core. We haven't changed anything about it.

Yes, because it's not meant to be run on `.mdx` files.

**Comment by antfu** [comment]
Well, if you say so, good luck then.

**Comment by JounQin** [comment]
I'm also trying to add more ESTree compatible MDX related node types start from https://github.com/mdx-js/eslint-mdx/pull/489

**Comment by JounQin** [comment]
> I'm also trying to add more ESTree compatible MDX related node types start from [mdx-js/eslint-mdx#489](https://github.com/mdx-js/eslint-mdx/pull/489)

@antfu CAN you reopen this issue and assign it me?

**Comment by antfu** [comment]
What's your plan for fixing it? I would think it's better to fix it on MDX side, unless it's very easy to fix here.

**Comment by JounQin** [comment]
I'm planning to fix it it `eslint-mdx`.

**Comment by antfu** [comment]
Not that I do not trust you, but I don't think it's a good reason to join an org just to transfer away an issue. Why not just create another issue on mdx and link to this one?

**Comment by JounQin** [comment]
> Why not just create another issue on mdx and link to this one?

It's not the reason, it's the benefit effect if I joined.
