### ISSUE TITLE
Add `maintainIndent` to `jsx-one-expression-per-line`

### ISSUE THREAD

**Issue by exoRift** [eslint-stylistic/eslint-stylistic#242]
### Clear and concise description of the problem

`--fix` for this rule will place literal text at indentation 0

### Suggested solution

Add an option that will maintain indentation for literals

### Alternative

Have a `jsx-literal-indentation` rule

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
Can you elaborate more and provide some examples? Ideally line-breaks rules only focus about line-breaks and leave the indentation to indent rules to fix.

**Comment by exoRift** [comment]
> Can you elaborate more and provide some examples? Ideally line-breaks rules only focus about line-breaks and leave the indentation to indent rules to fix.

If you have the following:

```jsx
<div>first literal {some_variable} second literal</div>
```

It becomes

```jsx
<div>
first literal
  {' '}
  {some_variable}
  {' '}
second literal
</div>
```

Note the missing indentation on the literals

**Comment by antfu** [comment]
I see; I think it should be handled by `jsx-indent` or `indent`; you could create a reproduction for them

**Comment by exoRift** [comment]
So should I repurpose this issue into an `includeLiterals` option for `jsx-indent`?

**Comment by antfu** [comment]
Sure. I think it would be better to create a new issue and linking to this one, to make it less confusing.

**Comment by antfu** [comment]
Close in favor of #250
