### ISSUE TITLE
`@eslint-stylistic/svelte`: eslint-stylistic plugin for Svelte's stylistic rules

### ISSUE THREAD

**Issue by eagerestwolf** [eslint-stylistic/eslint-stylistic#251]
### Clear and concise description of the problem

So, the Svelte team created an issue a while back [sveltejs/eslint-plugin-svelte#193][1] that proposed the idea of also depreciating their stylistic rules, much like `ESLint`, `@typescript-eslint`, and `eslint-plugin-react` have already done. Bringing this package in would bring the community one step closer to a unified monorepo for *most* things stylistic (obviously Vue, Solid, etc. still have their own stylistic rules...for now).

[1]: https://github.com/sveltejs/eslint-plugin-svelte/issues/193

### Suggested solution

In theory, the logical solution (assuming the `eslint-stylistic` team is on board) would be to extract the stylistic rules from `eslint-plugin-svelte` into a package within this repo (most likely `@eslint-stylistic/svelte`). I presented the option of running both this proposed new package and the existing stylistic rules in `eslint-plugin-svelte` for the time being, with the obvious intent to depreciate the existing rules eventually.

### Alternative

In my mind, the alternatives are basically either I maintain and publish the package on my own, which is counterproductive since the Svelte team could already do that themselves; or the Svelte rules stay with the Svelte team in the existing plugin.

### Additional context

While this would be a big undertaking, since it will require maintaining a 3rd AST within the repo, it should be a somewhat easy transition since the rules are already written. Granted, this will require coordinating with the Svelte team for some time on bug fixes since fixes will need to be deployed to both the main plugin and this plugin; however, Svelte has a new major version coming soon, so if we could get things done in time with sufficient time for everyone to make the transition, it should be possible to depreciate Svelte's stylistic rules with Svelte 5 (which is expected sometime in 2024). If this change is approved, I can handle the transition to bring the existing Svelte rules in; work on the Svelte issues; and try my best to keep up with Svelte's issues as well. Maybe this can serve as the unofficial canary branch (i.e. deploy the bug fixes here first, the backport them to `eslint-plugin-svelte`) until the transition is complete. That said, even if this issue is given the green light, I won't make any moves until the Svelte team okays everything on their end.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
Thanks for bringing this up, but I think this would be out-of-scope for this project. 

Framework-specific rules should be handled by their integrations as they are kinda coupled with framework implementation as well as the versions (Vue 2 vs 3, Svelte 4 vs 5, etc). Meanwhile, we can't possibly maintain custom syntaxes for all frameworks.

Whether Svelte would separate the plugin into two or so (it seems less likely according to the comments), they should better be in Svelte's monorepo or org, but not here. Here we maintain the general rules for JS, TS and JSX that works across frameworks.
