### ISSUE TITLE
Port stylistic rules from `eslint-plugin-vue`

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-stylistic/eslint-stylistic#253]
[`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) is disabling rules from [`eslint-plugin-vue`](https://github.com/vuejs/eslint-plugin-vue)

https://github.com/prettier/eslint-config-prettier/blob/main/index.js#L76-L112

**Comment by antfu** [comment]
Currently, we don't feel confident about taking framework-specific rules, as they will be more coupled with the framework and iterates faster than JS/TS.

https://github.com/eslint-stylistic/eslint-stylistic/issues/251#issuecomment-1873393608
