### ISSUE TITLE
`ts/padding-line-between-statements`: support enum

### ISSUE THREAD

**Issue by ddrozdov** [eslint-stylistic/eslint-stylistic#263]
### Clear and concise description of the problem

The rule currently can't check and fix empty lines before / after TS enum declaration.

### Suggested solution

Add `enum` to supported statement types.

### Alternative

None.

### Additional context

Easily resolved by adding these lines:
```
  'enum': newKeywordTester(
    AST_NODE_TYPES.TSEnumDeclaration,
    'enum',
  ),
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by 9romise** [comment]
Has been fixed by #453.
