### ISSUE TITLE
[qustion] ts vs js rules

### ISSUE THREAD

**Issue by zzzgit** [eslint-stylistic/eslint-stylistic#264]
Why does `@stylistic/eslint-plugin-js` has much more rules than `@stylistic/eslint-plugin-js`.

Can I think of that js rules will works in ts as well, so, ts rules is much less?

**Comment by antfu** [comment]
TS rules extends JS rules to add TS specific syntax support. Some JS rules does not have TS version because they don't have TS-sepcific things to handle (a.k.a they work well in TS). 

I'd suggest you to use https://eslint.style/packages/default so you don't even need to worry about this.
