### ISSUE TITLE
Shared config: setting semi: true has no effect on member-delimiter-style

### ISSUE THREAD

**Issue by IGx89** [eslint-stylistic/eslint-stylistic#266]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hello! When used the shared config and setting semi: true, member-delimiter-style still is configured with delimiter: none. That seems inconsistent to me. Would it make more sense to adjust that rule to use a semi delimiter in that situation, like the rule default options are?

### Reproduction

https://stackblitz.com/edit/github-yxmjyz?file=src%2Findex.ts

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
That's what I mean :) We should provide the options based on the condition, PR welcome

**Comment by IGx89** [comment]
Thanks for being so open to PRs! PR submitted: #267.
