### ISSUE TITLE
`customize`: read `StylisticCustomizeOptions` from the eslint configuration file, such as `settings` field

### ISSUE THREAD

**Issue by pikadun** [eslint-stylistic/eslint-stylistic#277]
### Clear and concise description of the problem

If I use the json format configuration file supported by eslint, I will not be able to use the `Configuration Factory` to customize the rules.

### Suggested solution

So consider reading `StylisticCustomizeOptions` from the configuration file first.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I am sorry but this is not possible as the timing is different. When the factory runs, it's constructing the configs array - which means it can't the setting read from the configs - it's like the chicken and egg problem. With the new flat config, I believe you will need to use the js config.
