### ISSUE TITLE
eslint-stylistic v1.6.0 is not compatible with Node v16.0

### ISSUE THREAD

**Issue by PCStefan** [eslint-stylistic/eslint-stylistic#278]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

#### Overview
I am working on a project that still uses Node v16.
However, the last release has introduced a major break change. Hence, breaking the versioning convention of using `^1.5.6` within `package.json` file.
  
---
  
#### Issue
*Node v16 is no longer supported due to update of the `espree` dependency required by the `packages/eslint-plugin-js` package
> Please see this change introduced in v1.6.0: 
> - https://github.com/eslint-stylistic/eslint-stylistic/blame/main/packages/eslint-plugin-js/package.json#L118
> - https://github.com/eslint-stylistic/eslint-stylistic/blame/v1.6.0/pnpm-lock.yaml#L248

I see that all of the other `espree` dependency are still using 9.6.1 but this one has been upgraded. 
  
---
  
#### Espree v10
espree v10 is a npm package that only works with Node v18 and above from v10.
> https://github.com/eslint/espree/blob/main/CHANGELOG.md#1000-2024-01-25
  
  
--- Reproduction steps
> I cann't really reproduce it on Stackblitz as it an environment issue. So, within the reproduction bit, I have only added the engine requirement in the package.json's engines section.

### Reproduction

https://stackblitz.com/edit/github-caghlk?file=package.json

### Contributes

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Oh good catch! We should revert `espree` then, until next major for ESLint v9. PR welcome if you want to help

**Comment by PCStefan** [comment]
Hi

I have opened the following pull request to address this issue: 
- https://github.com/eslint-stylistic/eslint-stylistic/pull/279
