### ISSUE TITLE
`indent`: Control ternary expressions indentation

### ISSUE THREAD

**Issue by djibarian** [eslint-stylistic/eslint-stylistic#293]
### Clear and concise description of the problem

So far I can't find a way of defining the indent of a ternary expression like this:

```
foo ?
bar :
paz
```

Whether it can be disabled completely with `ignoredNodes: ['ConditionalExpression']` or written as

```
foo ?
    bar :
    paz
```

### Suggested solution

Add a new option "ConditionalExpression" (default: 1) to be able to control the indentation of the ternary expression. For the case above it could be set to 0. This would align with other options like "SwitchCase" or "MemberExpression".

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by laruiss** [comment]
Isn’t the `offsetTernaryExpressions` option that you are looking for?

If it is, I have a problem to make it work, it seems...

![image](https://github.com/user-attachments/assets/c2fbe5ca-bd2b-4239-82f5-a8318ee7a3aa)

**Comment by 9romise** [comment]
https://eslint.style/rules/default/indent#offsetternaryexpressions can control ternary expressions indentation.
