### ISSUE TITLE
Add airbnb config using plugins rules

### ISSUE THREAD

**Issue by wesleyschlenker** [eslint-stylistic/eslint-stylistic#297]
### Clear and concise description of the problem

It would be nice to have a config with this plugin's rules emulating the Airbnb style guide instead of having to copy their whole ruleset and tweak it to no longer use deprecated rules. It's not possible to get all the way to Airbnb style with just the configuration factory.

### Suggested solution

Create a default config mirroring [airbnb's style rules](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js).

### Alternative

Add enough options to the configuration factory to reach Airbnb style that way.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I think it would be easier for Airbnb to update their config to migrate over - we can't fork and maintain every config set (hard to sync with as well) - it's also not in the scope of this project.

**Comment by Solant** [comment]
Hey, sorry for necrobumping

If you still need AirBnb style, I created a port of original airbnb eslint rules using @stylistic plugin rules

https://www.npmjs.com/package/eslint-stylistic-airbnb
