### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by antfu** [eslint-stylistic/eslint-stylistic#36]
We are thinking of releasing 1.0 the next week with the current state (1:1 migration from each repo) so that users could be more confidently migrate over, if no major bug/issue occurs before that.

A few future plans in my head:

- `v1.0.0`
  - 1:1 migration from each source project
- `v2.0.0`
  - Rewrite in TS with unified tooling
- `v3.0.0`
  - Merge TS and JS rules into one. Soft deprecate js/ts standalone packages.

**Comment by ywenhao** [comment]
It is good!

**Comment by silverwind** [comment]
> Merge TS and JS rules into one. Soft deprecate js/ts standalone packages.

Would this introduce a dependency of the TS parser for JS users? I'm not particularily fond of it because it is like twice as slow with no benefits for JS.

**Comment by ota-meshi** [comment]
> Would this introduce a dependency of the TS parser for JS users?

I think the answer is no. There is no parser dependency for `@stylistic/eslint-plugin-ts` at now.
You can choose any parser you like. You can also use babel even if you have ts files.

https://github.com/eslint-stylistic/eslint-stylistic/blob/1077846d62b7d7469f7dd4d8ef967733e4d5a9d6/packages/eslint-plugin-ts/package.json#L43

**Comment by silverwind** [comment]
>  You can choose any parser you like. You can also use babel even if you have ts files.

Good to hear. I'm using the `espree` for JS and `@typescript-eslint/parser` for TS. Best of both worlds this way.

**Comment by antfu** [comment]
Everything seems to be working fine. Cut the release now so we can start iterating!
https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v1.0.0
