### ISSUE TITLE
doc error 404 page for new rule 

### ISSUE THREAD

**Issue by TheElegantCoding** [eslint-stylistic/eslint-stylistic#381]
the new rule `jsx-function-call-newline` in this url is 404, no doc available

https://eslint.style/packages/eslint-plugin-jsx/rules/jsx-function-call-newline

**Comment by antfu** [comment]
Where did you get that link? It should be https://eslint.style/rules/jsx/jsx-function-call-newline

**Comment by TheElegantCoding** [comment]
i get it from https://eslint.style/packages/eslint-plugin-jsx/rules

**Comment by antfu** [comment]
But where did you get that link? Ideally you should visit https://eslint.style/packages/jsx#rules instead 🤣

**Comment by TheElegantCoding** [comment]
i search in the home page the new rule `jsx-function-call-newline`, the first result go to that link
