### ISSUE TITLE
Link to Contribution on Github

### ISSUE THREAD

**Issue by aisevim** [eslint-stylistic/eslint-stylistic#382]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hi 🙌,

Not real Bug, more UX issue:
In the Documentation, navigate to Header v1.8.0 > click on Contributing > Github Contributing page > return to docs 🥲.

I believe it's unnecessary to direct users to the "Github Contribution page" with this instruction:
"Please refer to https://eslint.style/contribute/guide for more information."

This may negatively impact the user experience. Before creating a pull request to replace or delete the link, I would like to get your feedback on this. Is this already known? If so, why?

Thanks 😄,

### Reproduction

navigate to Header v1.8.0 > click on Contributing > Github Contributing page > return to docs

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [x] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Nice catch, I think in the nav bar we could directly reference to the guide page. Feel free to send the PR. Thanks
