### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by Rilivaine** [eslint-stylistic/eslint-stylistic#387]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When installing last versions ESLint (9.2.0) and ESLint Stylistic (2.0.0), I'm getting unmet peer warning.

```
 WARN  Issues with peer dependencies found
.
└─┬ @stylistic/eslint-plugin 2.0.0
  └─┬ @stylistic/eslint-plugin-ts 2.0.0
    └─┬ @typescript-eslint/utils 7.8.0
      └── ✕ unmet peer eslint@^8.56.0: found 9.2.0
```

### Reproduction

Install ESLint and Stylistic with `pnpm add`

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
This is up to `typescript-eslint`, they are not officially support ESLint v9 yet (but in fact it works). 

- https://github.com/typescript-eslint/typescript-eslint/issues/8211

You can just ignore the warning for now.

**Comment by xavierfoucrier** [comment]
I can confirm the issue.

![Capture d'écran 2024-06-03 175001](https://github.com/eslint-stylistic/eslint-stylistic/assets/2471223/d191d24a-b42a-4790-b144-cddcdf8bf528)

**Comment by ljharb** [comment]
You shouldn't ever ignore peer dep warnings; if all your stuff isn't compatible with eslint 9 yet, what you should do is simply not upgrade to eslint 9 yet. There's no rush.

**Comment by xavierfoucrier** [comment]
@ljharb of course yes, but I am planning a pull request to upgrade to v9 in most of my projects before really migrating to v9 as well, kind of anticipating, so it would be nice to see this "issue" fixed.
