### ISSUE TITLE
`sort-keys`: Auto fixable version of the sort keys rule

### ISSUE THREAD

**Issue by Jelmerro** [eslint-stylistic/eslint-stylistic#394]
### Clear and concise description of the problem

In the base Eslint, it has been suggested a lot of times to make the [sort-keys](https://eslint.org/docs/latest/rules/sort-keys) rule be auto-fixable, yet it was always rejected as "too stylistic" for the core project. Since this project's main goal is to maintain the stylistic rules eslint does not want to maintain in core, I would be delighted to have this rule be auto-fixable. There are numerous plugins to be found on github, but none of them seem to be actively maintained.

### Suggested solution

Include the sort-keys rule in eslint-stylistic and give it the option to automatically fix errors, similar to packages like this that are rarely updated: https://github.com/leo-buneev/eslint-plugin-sort-keys-fix

### Alternative

Using outdated plugins, though I would highly prefer it to be included in stylistic.

### Additional context

I tried searching for duplicates, but could not find one. My apologies if I may have failed in my search. As for making a PR, it probably depends if we are license-wise allowed to copy over existing plugins, though I have not familiarized myself with the stylistic code styles as of yet.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
There is a much better alternative: https://eslint-plugin-perfectionist.azat.io/

I also have a granular version, where you can lint and fix per object: https://eslint-plugin-command.antfu.me/commands/keep-sorted

I think the case is that `sort-keys` is a rather old and imitated version of these fields. Working on it would end up exposing more edge cases - which eventually might end up duplicating the work in `eslint-plugin-perfectionist`, while on the other hand, we don't want it to work perfectly already and have someone actively working on it.

For now, unless someone sends a PR with affordable and maintainable solutions, I don't think we will support this any sooner.
