### ISSUE TITLE
`quotes`: add option to ignore string literals

### ISSUE THREAD

**Issue by remcohaszing** [eslint-stylistic/eslint-stylistic#400]
### Clear and concise description of the problem

I use Prettier for formatting. Prettier enforces a consistent quote style. However, Prettier does not enforce using string literals over template strings. To enforce this, I’m using the [`@stylistic/quotes`](https://eslint.style/rules/js/quotes) rule. The downside is that:

1. The configuration of `@stylistic/quotes` needs to match the Prettier configuration.
2. Incorrectly quoted strings are reported by both `@stylistic/quotes` and `eslint-plugin-prettier`.

### Suggested solution

Add an option `ignoreStringLiterals`. When this is used, only template literals are checked.

### Alternative

Don’t do anything :shrug: 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
So you want ESLint to enforce the use of literal quotes whenever possible for template strings, but don't care about which quotes to use, right?

If it's a few lines of code I don't mind to have them - PR welcome :)_

**Comment by remcohaszing** [comment]
Exactly!

PR submitted :)
