### ISSUE TITLE
`imports-first`: force imports statements to be at the beginning

### ISSUE THREAD

**Issue by Ericlm** [eslint-stylistic/eslint-stylistic#463]
### Clear and concise description of the problem

I want to have all my imports at the same place (top of the script), without having the possibility to declare imports anywhere else in the script.

### Suggested solution

In `imports-first` or `import-top`, we could detect each import statement and force it to be at the top of the file. That would also allow rules like [sort imports](https://eslint-plugin-perfectionist.azat.io/rules/sort-imports) to work better with a single imports "block".

### Alternative

- I could use the import/first rule, but I dropped eslint plugin import as it's not eslint 9 compatible.
- Verifying manually that the imports are all on top.

### Additional context

- It's linked to an issue I have with sort-imports : https://github.com/azat-io/eslint-plugin-perfectionist/issues/157, but I think it's something stylistic is more tailored for.
- It wouldn't change runtime because of imports hoisting
- Maybe a mirroring rule for having `export` at the end?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by 9romise** [comment]
Maybe you can use [`eslint-plugin-import-x`](https://github.com/un-ts/eslint-plugin-import-x).
https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/first.md
https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/exports-last.md

**Comment by Ericlm** [comment]
Thank you for your suggestions, it looks promising! I'll still leave this issue open I think, like it's more a "stylistic" preference 🤔
