### ISSUE TITLE
`no-multi-spaces` conflicts with `key-spacing`

### ISSUE THREAD

**Issue by dmke** [eslint-stylistic/eslint-stylistic#490]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

*(This may be related to #476, but I'm not sure)*

The following rules cause a formatting conflict:

```
'@stylistic/key-spacing':     ['error', { align: 'value' }],
'@stylistic/no-multi-spaces': ['error', { exceptions: { Property: true } }],
```

Running `eslint` on the following code (see full reproduction on Stackblitz below):

```ts
export interface User {
  id: number
  name: string
}
```

yields

```
/home/projects/gqairrokjj.github/src/index.ts
  2:3  error  Missing space before value for key 'id'  @stylistic/key-spacing
```

and on the following code

```ts
export interface User {
  id:   number
  name: string
}
```

`eslint` yields

```
/home/projects/gqairrokjj.github/src/index.ts
  2:6  error  Multiple spaces found before 'number'  @stylistic/no-multi-spaces
```

I expect the latter code example to be free of formatting issues.

### Reproduction

https://stackblitz.com/edit/github-7uuvt3?file=eslint.config.js

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by ghs** [comment]
Same here

**Comment by dmke** [comment]
As per #245, this seems to stem from using `@typescript-eslint/parser`, which changes some AST node types.

Adding `TSTypeAnnotation: true` to the `exceptions` of `@stylistic/no-multi-spaces` does the trick for me:

```js
'@stylistic/no-multi-spaces': ['error', {
  exceptions: {
    Property:         true,
    TSTypeAnnotation: true,
  }
}]
```
