### ISSUE TITLE
`@stylistic/js/indent`: relative indent

### ISSUE THREAD

**Issue by mathcovax** [eslint-stylistic/eslint-stylistic#508]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hello, problem with this rule definition : 
![image](https://github.com/user-attachments/assets/56d96408-7da6-4896-89ee-b7d72bc98fa2)

this causes a relative indentation:
![image](https://github.com/user-attachments/assets/938f5f6f-5f67-4f07-a045-3554e816741f)
![image](https://github.com/user-attachments/assets/b16e0299-4f54-4657-ac58-189035edb9a8)
![image](https://github.com/user-attachments/assets/cd46d70d-aef6-4199-aae6-5696050482c5)
![image](https://github.com/user-attachments/assets/12a4bc2a-43ed-4333-8175-095015d0c1c2)

the desired result is this:
![image](https://github.com/user-attachments/assets/f84acfb1-8356-431f-a568-fefe7ccdc0e6)

maybe the number of indentation inside blocks is about another rule?
Thank you for your work.

All my rules : https://github.com/duplojs/eslint/blob/main/scripts/index.ts

edit: cause by type déclaration in block
### Reproduction

See pictures.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
You should use `@stylistic/ts/indent` or `@stylistic/indent` - as `@stylistic/js/indent` does not handle TypeScript syntaxes
