### ISSUE TITLE
`jsx-uses-vars`: Check if a variable is used as jsx

### ISSUE THREAD

**Issue by ImJiaWenKai** [eslint-stylistic/eslint-stylistic#547]
### Clear and concise description of the problem

If I use the no-unused-vars rule, when I import a react component and use it, eslint does not accurately detect that I use it in jsx. So I had to solve this problem by installing eslint-plugin-react and configuring react/jsx-uses-vars. I hope stylistic can adapt to this rule as soon as possible. Thanks
<img width="517" alt="image" src="https://github.com/user-attachments/assets/c3224f35-5fc8-4a8b-bbeb-991562d93316">
<img width="579" alt="image" src="https://github.com/user-attachments/assets/df612a93-4241-4344-a28f-e219fd9aa74f">

### Suggested solution

Learn from eslint-plugin-react and support this rule

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [x] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by 9romise** [comment]
Tbh, I think it's not a stylistic rule but a jsx-related rule.
So `eslint-plugin-react` or [`@eslint-react/eslint-plugin`](https://github.com/Rel1cx/eslint-react) is a better choice.
