### ISSUE TITLE
@stylistic/operator-linebreak  无法生效得问题

### ISSUE THREAD

**Issue by zdjzpg** [eslint-stylistic/eslint-stylistic#557]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

![Snipaste_2024-10-10_13-05-42](https://github.com/user-attachments/assets/fd6ec8dc-3533-44fc-9920-30e789e601dc)
![Snipaste_2024-10-10_13-05-58](https://github.com/user-attachments/assets/d5a8d568-1de8-4da3-8549-7997eb5a4cc6)
设置了@stylistic/operator-linebreak，代码里仍然提示 “&&"
should be placed at the beginning of the line.eslint(@stylistic/operator-linebreak)

### Reproduction

暂无

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by 9romise** [comment]
Please give more info.
I try this in the [repo-template](https://github.com/eslint-stylistic/repro-template), and it works well.
![image](https://github.com/user-attachments/assets/e27aad98-82a4-441e-b3c2-75a3d3574735)
![image](https://github.com/user-attachments/assets/7b4dcfc8-8f29-4e96-bfbe-2d8392420c08)

**Comment by 9romise** [comment]
closed, will reopen if it can be reproduced
