### ISSUE TITLE
Support ESLint 9

### ISSUE THREAD

**Issue by darthmaim** [eslint-stylistic/eslint-stylistic#561]
ESLint 8 has reached [EOL on October 5th](https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/#eslint-v8.x-end-of-life-is-october-5%2C-2024), and ESLint 9 has been [available since April 5th](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/).

All packages in this repository still list ESLint 8 as peer dependency.

```json
"peerDependencies": {
  "eslint": ">=8.40.0"
},
```

What is the plan to support ESlint 9?

**Comment by antfu** [comment]
`>=8` includes 9. This project supports ESLint 9 from the day one.

**Comment by darthmaim** [comment]
You are right, sorry, my bad!
