### ISSUE TITLE
The default configuration of the `arrowParens` rule does not match the documentation description

### ISSUE THREAD

**Issue by laofas** [eslint-stylistic/eslint-stylistic#572]
https://github.com/eslint-stylistic/eslint-stylistic/blob/3db4870f56b5f999439987eb904361488e764cc6/packages/eslint-plugin/configs/customize.ts#L19
https://github.com/eslint-stylistic/eslint-stylistic/blob/3db4870f56b5f999439987eb904361488e764cc6/packages/eslint-plugin/configs/customize.ts#L34

Document location: https://eslint.style/rules/default/arrow-parens#options

<img width="723" alt="image" src="https://github.com/user-attachments/assets/c7d96a58-4719-4ad5-bbf4-ad7385e9dbce">

**Comment by 9romise** [comment]
`customize` is just a [**factory function**](https://eslint.style/guide/config-presets#configuration-factory).
The default config you mentioned is just the default value for that function.

The defualt option of the rule (arrow-parens) is here: 
https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/rules/arrow-parens/arrow-parens._js_.ts#L59

**Comment by laofas** [comment]
I see that the shared configuration `recommended-flat` is created by this `customize` factory function, and by default the `arrow-parens` rule for this configuration is `as-needed`, but the default value written in the documentation is `always`, so I'm not sure if this is correct?

**Comment by 9romise** [comment]
I think that is correct. The default option in the document is the default option of the **rule** but not the **factory function**.

**Comment by laofas** [comment]
Ok, thank you for your explanation, I will close this issue

**Comment by danilomourelle** [comment]
It would be really nice to have the default in document be the same as in factory function. A not just for this rule. I just found out that `brace-style` has the same behaviour
