### ISSUE TITLE
`no-empty-function`: incompatible with eslint 9.15.0

### ISSUE THREAD

**Issue by Choppel** [eslint-stylistic/eslint-stylistic#611]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When using the latest version of @stylistic/eslint-plugin-ts (2.10.1) together with eslint 9.15.0 there are type errors:
`Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow')`

With eslint 9.14.0 everything works as expected.

### Reproduction

Try using the plugin together with eslint 9.15.0 and configure the rule 'no-empty-function'. It should throw errors as described above.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by 9romise** [comment]
This doesn't seem to be an issue with `eslint-stylistic`, it seems to be the similar to https://github.com/eslint/eslint/issues/19134.

**Comment by danielrentz** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/10338

**Comment by ntnyq** [comment]
Bump @typescript-eslint/plugin to 8.15.0
