### ISSUE TITLE
`indent`: Inconsistent behavior of `offsetTernaryExpressions`

### ISSUE THREAD

**Issue by loongzhu** [eslint-stylistic/eslint-stylistic#621]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

same problem with deprecated  eslint indent https://github.com/eslint/eslint/issues/19156#issuecomment-2493243219

![image](https://github.com/user-attachments/assets/48bba594-5bcb-4f62-85a6-8707564b8a7a)

run `eslint --fix`:

![image](https://github.com/user-attachments/assets/104e7798-6786-41dc-bce1-bc139f5be7d5)

### Reproduction

https://stackblitz.com/edit/github-ahrwxz?file=eslint.config.js,src%2Findex.ts,package.json

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by voxpelli** [comment]
Is this a fix for https://github.com/eslint/eslint/issues/14058 ?
