### ISSUE TITLE
brace-style规则的默认值，文档与代码不一致

### ISSUE THREAD

**Issue by gitsheny** [eslint-stylistic/eslint-stylistic#624]
https://github.com/eslint-stylistic/eslint-stylistic/blob/2d8d8ce57a12b597de1cffab8e9784b8e20fca15/packages/eslint-plugin/configs/customize.ts#L21

代码中的默认值是stroustrup，而文档中描述的默认值是1tbs

https://github.com/eslint-stylistic/eslint-stylistic/blob/2d8d8ce57a12b597de1cffab8e9784b8e20fca15/packages/eslint-plugin/rules/brace-style/README._js_.md?plain=1#L59

**Comment by 9romise** [comment]
similar to #609, #572
