### ISSUE TITLE
docs: `func-call-spacing` and `function-call-spacing` are duplicates,

### ISSUE THREAD

**Issue by loongzhu** [eslint-stylistic/eslint-stylistic#629]
### Additional context

`func-call-spacing` and `function-call-spacing` are duplicates
`func-call-spacing` will redirect to `function-call-spacing`

![image](https://github.com/user-attachments/assets/aa8fda69-2180-4a22-a32b-bd7a69f2a8b3)

**Comment by 9romise** [comment]
`func-call-spacing` was renamed to `function-call-spacing` when migrating from the `ESLint` repository.
So they coexist to ensure users migrating from `ESLint` can still find this rule.
Also, `metadata` is generated by script, you should not edit it directly.
