### ISSUE TITLE
2.12.0 is not published in NPM

### ISSUE THREAD

**Issue by zloirock** [eslint-stylistic/eslint-stylistic#632]
<img width="780" alt="2024-12-08 в 23 50 50" src="https://github.com/user-attachments/assets/f53de0fe-c77d-4a79-9331-4a3b72027b0a">

<img width="483" alt="2024-12-08 в 23 51 27" src="https://github.com/user-attachments/assets/cdbe67c6-437b-4047-99b8-40f274972c2e">

**Comment by antfu** [comment]
NPM was down at the time we where doing the release. Should be good now.
