### ISSUE TITLE
Stylistyc rules should disable original rules

### ISSUE THREAD

**Issue by hazzik** [eslint-stylistic/eslint-stylistic#68]
I have a problem with overriding rules coming from [`eslint-config-standard`](https://www.npmjs.com/package/eslint-config-standard) that is using deprecated eslint rules.

For example, standard has defined that quotes should be single quotes. But we prefer double quotes.

This is simplified version of our config that used to work great:
.eslintrc.yml:
```yaml
extends: standard
rules: 
  quotes: [error, double]
```

Now, if I want to migrate from the deprecated `quotes` rule to `@stylistic/quotes` I'm getting a configuration that is always invalid no matter the state of the code.

.eslintrc.yml:
```yaml
extends: standard
plugins:
  - "@stylistic"
rules: 
  "@stylistic/quotes": [error, double]
```

So, if my index.js file looks like this: 
```js
console.log("hello world")
```
Then I'm getting following error
```log
$ yarn eslint --fix index.js 
yarn run v1.22.19
$ /home/hazzik/repos/xxx/node_modules/.bin/eslint --fix index.js

/home/hazzik/repos/xxx/index.js
  1:13  error  Strings must use singlequote  quotes

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
And if I use single quotes:
```js
console.log('hello world')
```
```log
$ yarn eslint --fix index.js 
yarn run v1.22.19
$ /home/hazzik/repos/xxx/node_modules/.bin/eslint --fix index.js

/home/hazzik/repos/xxx/index.js
  1:13  error  Strings must use doublequote  @stylistic/quotes

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by antfu** [comment]
In ESLint, a rule can't know if another rule is enabled or not, and certainly there is no way for us to disable other rules. We already provided the migration plugin if you maintain your own config file: https://eslint.style/guide/migration#eslint-migrate-plugin

**Comment by hazzik** [comment]
Then this plugin is, unfortunately, completely unusable. 

> We already provided the migration plugin if you maintain your own config file

If that was not clear - I have migrated my config, but, unfortunately, I depend on other configs that use deprecated rules.  `eslint-config-standard` and `quotes` were just for an example.

> a rule can't know if another rule is enabled or not, and certainly there is no way for us to disable other rules. 

This is not true. There are ways, like [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer/).

**Comment by antfu** [comment]
> [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer/)

This is for creating new rules, **not overriding the config**.

If you are able to find a way, PR is always welcome. Otherwise, I can't help on things I consider technically impossible.

**Comment by hazzik** [comment]
> This is for creating new rules, not overriding the config.

That plugin allows a way to override behavior of old rules in a way it is compatible with the new rules by monkey patching them. 

In any way, the @stylistic is completely unusable as for now if one uses any predefined third party configs. After migration I have ~20,000 conflicting errors and thousands of lines of unwanted changes (where rules do not explicitly conflict).
