### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by antfu** [eslint-stylistic/eslint-stylistic#70]
https://github.com/eslint-stylistic/eslint-stylistic/pull/66 has done the initial work and tooling setup to bundle and type checking.

We still have many rules rewritten in JavaScript. Help would be much appreciated!

If you want to help, please feel free to leave a comment below to say what rule you want to migrate, and send PRs to the main branch, **one PR for a rule**.

Migration examples:

- Rules of `eslint-plugin-js`: https://github.com/eslint-stylistic/eslint-stylistic/commit/a88038ef8dcd854c79697381587a8932864b645c#diff-1c7f529705777d91ed7afa4e5549f6aebc607177bf49bd9f7c19d6c614defd4d
- Rules of `eslint-plugin-jsx`: https://github.com/eslint-stylistic/eslint-stylistic/commit/a88038ef8dcd854c79697381587a8932864b645c#diff-f2ed5fbe59b664a37dd073cd140a7dd6812bc40757dd51f84a6fc3407becd0a7

**Comment by Namchee** [comment]
I think we need a rule tracker for this. Below are the list of rules separated by its packages. Checked rules indicates the the rule has been successfully migrated to TypeScript.

## `@stylistic/js`

- [x] `array-bracket-newline`
- [ ] `array-bracket-spacing`
- [ ] `array-element-newline`
- [ ] `arrow-parens`
- [ ] `arrow-spacing`
- [ ] `block-spacing`
- [ ] `brace-style`
- [ ] `comma-dangle`
- [ ] `comma-spacing`
- [ ] `comma-style`
- [ ] `computed-property-spacing`
- [x] `dot-location`
- [ ] `eol-last`
- [ ] `func-call-spacing`
- [ ] `function-call-argument-newline`
- [ ] `function-call-spacing`
- [ ] `function-paren-newline`
- [ ] `generator-star-spacing`
- [ ] `implicit-arrow-linebreak`
- [ ] `indent`
- [ ] `jsx-quotes`
- [ ] `key-spacing`
- [ ] `keyword-spacing`
- [ ] `linebreak-style`
- [ ] `lines-around-comment`
- [ ] `lines-between-class-members`
- [ ] `max-len`
- [ ] `max-statements-per-line`
- [ ] `multiline-ternary`
- [ ] `new-parens`
- [ ] `newline-per-chained-call`
- [ ] `no-confusing-arrow`
- [ ] `no-extra-parens`
- [ ] `no-extra-semi`
- [ ] `no-floating-decimal`
- [ ] `no-mixed-operators`
- [ ] `no-mixed-spaces-and-tabs`
- [ ] `no-multi-spaces`
- [ ] `no-multiple-empty-lines`
- [ ] `no-tabs`
- [ ] `no-trailing-spaces`
- [ ] `no-whitespace-before-property`
- [ ] `nonblock-statement-body-position`
- [ ] `object-curly-newline`
- [ ] `object-curly-spacing`
- [ ] `object-property-newline`
- [ ] `one-var-declaration-per-line`
- [ ] `operator-linebreak`
- [ ] `padded-blocks`
- [ ] `padding-line-between-statements`
- [ ] `quote-props`
- [ ] `quotes`
- [ ] `rest-spread-spacing`
- [ ] `semi`
- [ ] `semi-spacing`
- [ ] `semi-style`
- [ ] `space-before-blocks`
- [ ] `space-before-function-paren`
- [ ] `space-in-parens`
- [ ] `space-infix-ops`
- [ ] `space-unary-ops`
- [ ] `spaced-comment`
- [ ] `switch-colon-spacing`
- [ ] `template-curly-spacing`
- [ ] `template-tag-spacing`
- [ ] `wrap-iife`
- [ ] `wrap-regex`
- [ ] `yield-star-spacing`

## `@stylistic/jsx`

- [x] `jsx-child-element-spacing`
- [ ] `jsx-closing-bracket-location`
- [ ] `jsx-closing-tag-location`
- [ ] `jsx-curly-brace-presence`
- [ ] `jsx-curly-newline`
- [ ] `jsx-curly-spacing`
- [ ] `jsx-equals-spacing`
- [ ] `jsx-first-prop-new-line`
- [ ] `jsx-indent`
- [ ] `jsx-indent-props`
- [ ] `jsx-max-props-per-line`
- [ ] `jsx-newline`
- [ ] `jsx-one-expression-per-line`
- [ ] `jsx-props-no-multi-spaces`
- [ ] `jsx-self-closing-comp`
- [ ] `jsx-sort-props`
- [ ] `jsx-tag-spacing`
- [ ] `jsx-wrap-multilines`

**Comment by Namchee** [comment]
I'll migrate `func-call-spacing`

**Comment by auvred** [comment]
`no-extra-parens` for now blocked by https://github.com/eslint-community/eslint-utils/pull/60
Because `@eslint-community/eslint-utils` doesn't have type declarations (or we can just make temporary declarations for it on our end)
 https://github.com/eslint-stylistic/eslint-stylistic/blob/1e62a46b457dbd12f6cd07ac1ce0f8986d84411d/packages/eslint-plugin-js/rules/no-extra-parens/no-extra-parens.js#L10

**Comment by antfu** [comment]
@auvred We could add a simple declaration for that function we use

**Comment by antfu** [comment]
If you want to check what is remaining, you can run `npx esno scripts/list-js.ts`:

<img width="830" alt="image" src="https://github.com/eslint-stylistic/eslint-stylistic/assets/11247099/7fb9a7cb-f8f8-48a6-98ef-f79240ce004d">

**Comment by alexzhang1030** [comment]
Looks like the rules of `js` and `jsx` are all migrated, congratulations!

<img width="913" alt="image" src="https://github.com/eslint-stylistic/eslint-stylistic/assets/49969959/1240f827-fed4-407c-bed0-58b52fa46299">

**Comment by antfu** [comment]
We made it! Thanks everyone for your contributions! @Namchee @alexzhang1030 @auvred @ntnyq @starknt @kecrily @Dhoni77 @coderwyd @albizures @aldillek
