### ISSUE TITLE
Auto-fix for `style/max-len`

### ISSUE THREAD

**Issue by DamianGlowala** [eslint-stylistic/eslint-stylistic#73]
It would be a great enhancement being able to auto-fix `style/max-len` linting errors without having to use Prettier.

**Comment by ljharb** [comment]
I'm not sure this is a great approach; prettier's attempt to "fix" this results in much uglier code much of the time.

I think there should be different rules around when arrays/objects/function calls/function signatures/ternaries/imports/exports/etc should be single-line or multiline, and that if these are addressed, all the important use cases would be met without enabling max-len *at all*.

**Comment by antfu** [comment]
I don't think it will be trivial to support this, as it's hard to determine where to break the line. Having auto line-wrapping is the main reason driving me to move away from the Prettier. I personally have no interest in implementing that. If someone wants to give it a try, I would suggest to publish as a separate plugin and validate that idea in various projects. If that end up working well, I'd be happy to have it.

**Comment by DamianGlowala** [comment]
Thanks for both of your comments, closing!
